Reworked postinst, postrm and prerm files

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -2,18 +2,35 @@
 set -e
 
 if [ "$1" = "purge" ]; then
+    # Remove log and runtime files
     rm -f /var/log/lsyncd/lsyncd.log
     rm -f /var/run/lsyncd.status
-	rm -f /etc/lsyncd/lsyncd.conf.lua
-	rm -f /etc/lsyncd/includes/extra
-	rm -f /etc/lsyncd/includes/system
-	rm -f /etc/lsyncd/includes/user
-	rm -f /etc/logrotate.d/lsyncd-backup
-	rm -f /etc/systemd/system/lsyncd.service.d/override.conf
-	rm -f /usr/bin/lsync-merge-includes
-	rmdir --ignore-fail-on-non-empty /etc/lsyncd || true
-	rmdir --ignore-fail-on-non-empty /etc/systemd/system/lsyncd.service.d || true
+
+    # Remove configs and includes
+    rm -f /etc/lsyncd/lsyncd.conf.lua
+    rm -f /etc/lsyncd/includes/extra
+    rm -f /etc/lsyncd/includes/system
+    rm -f /etc/lsyncd/includes/user
+
+    # Remove logrotate file
+    rm -f /etc/logrotate.d/lsyncd-backup
+
+    # Remove systemd override
+    rm -f /etc/systemd/system/lsyncd.service.d/override.conf
+
+    # Remove helper script
+    rm -f /usr/bin/lsyncd-merge-includes
+
+    # Cleanup empty dirs
+    rmdir --ignore-fail-on-non-empty /etc/lsyncd/includes || true
+    rmdir --ignore-fail-on-non-empty /etc/lsyncd || true
+    rmdir --ignore-fail-on-non-empty /etc/systemd/system/lsyncd.service.d || true
     rmdir --ignore-fail-on-non-empty /var/log/lsyncd || true
+
+    # Tell systemd to forget overrides
+    if [ -x /bin/systemctl ] || [ -x /usr/bin/systemctl ]; then
+        systemctl daemon-reload || true
+    fi
 fi
 
 exit 0
